### PR TITLE
Notificaiton - > Notification

### PR DESCRIPTION
**Pull request by overlordbleck**

### CODE REVIEW

**Comment by overlordbleck** [comment]
Also for the `Buttons` notification type can we have more description for what the Color param does for the `AddButton` method @samuelWilliams99 ?

**Review by samuelWilliams99 — DISMISSED** [review]

**Comment by samuelWilliams99** [comment]
If that addbutton description is good with you, I'll merge

**Comment by overlordbleck** [comment]
image
Might be because of #5 but I don't see a background color

**Comment by samuelWilliams99** [comment]
Oh, I'll look into that

**Comment by samuelWilliams99** [comment]
~~Definitely a result of #5, fixing now~~ I'm wrong, It's the colour for the text, underline, and background colour for on click, I'll adjust the readme

**Review by samuelWilliams99 — APPROVED** [review]

**Pull request merged**
